name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: node:20-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun and timezone data
        run: |
          apk add --no-cache curl unzip bash github-cli
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: npm run test:ci

      - name: Build with Bun
        run: bun run build:no-tests

      - name: Upload to release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload '${{ github.event.release.tag_name }}' main.js manifest.json styles.css --clobber
