name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: oven/bun:1-alpine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: bun install --frozen-lockfile
    
    - name: Run build
      run: bun run build
    
    - name: Create release archive
      if: github.event_name == 'release'
      run: |
        mkdir -p release
        cp main.js release/
        cp manifest.json release/
        cp styles.css release/
        cd release
        zip -r ../create-or-open-file-obsidian-plugin.zip .
    
    - name: Upload to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./create-or-open-file-obsidian-plugin.zip
        asset_name: create-or-open-file-obsidian-plugin.zip
        asset_content_type: application/zip 