name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    container:
      image: node:20-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun and timezone data
        run: |
          apk add --no-cache curl unzip bash tzdata
          curl -fsSL https://bun.sh/install | bash
          export PATH="$HOME/.bun/bin:$PATH"
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests
        run: npm run test:ci

      - name: Build with Bun
        run: bun run build:no-tests

      - name: Create release archive
        if: github.event_name == 'release'
        run: |
          mkdir -p release
          cp main.js release/
          cp manifest.json release/
          cp styles.css release/
          cd release
          zip -r ../create-or-open-file-obsidian-plugin.zip .

      - name: Upload to release
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./create-or-open-file-obsidian-plugin.zip
          asset_name: create-or-open-file-obsidian-plugin.zip
          asset_content_type: application/zip
